from pathlib import Path

from flask import Flask, abort, render_template, send_from_dictionary, url_for

app = Flask(__name__)

STUDENT_NAME = "2AM_VL4D"

PROGRAMS = [
    {
        "id": 1,
        "slug": "first-gui",
        "title": "First Gui",
        "description": "this program shows what you write.",
        "long_description": "This is a simple Python Tkinter GUI application that lets the user enter text and update a label with it. The label’s text and color change when the button is clicked, demonstrating basic widgets, event handling, and interactive interfaces.",
        "category": "GUI",
        "version": "1.0.0",
        "icon": "images/icons/first-gui.svg",
        "screenshot": "images/screenshots/Screenshot first gui.png",
        "file_name": "downloads/firstGUI.exe",
        "author": STUDENT_NAME,
    },
 {
        "id": 2,
        "slug": "auto-clicker",
        "title": "Auto Clicker",
        "description": "Automatically clicks for you.",
        "long_description": "This Python Tkinter application is an Auto Clicker that simulates mouse clicks at a user-defined speed. Users can enter clicks per second, start the auto-clicking process, and stop it with the ESC key. The app demonstrates GUI design, event handling, and integration with mouse and keyboard libraries.",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/auto-clicker.svg",
        "screenshot": "images/screenshots/Screenshot auto clicker.png",
        "file_name": "downloads/autoclicker1.exe",
        "author": STUDENT_NAME,
    },
 {
        "id": 3,
        "slug": "calculator",
        "title": "Calculator",
        "description": "A simple calculator application.",
        "long_description": "This is a basic Python Tkinter calculator that performs addition, subtraction, multiplication, and division operations. It demonstrates the use of buttons, entry fields, and label widgets to create a functional user interface.",
        "category": "GUI",
        "version": "1.0.0",
        "icon": "images/icons/calculator.svg",
        "screenshot": "images/screenshots/Screenshot calculator.png",
        "file_name": "downloads/calculator.exe",
        "author": STUDENT_NAME,
    },
 {
        "id": 4,
        "slug": "game-launcher",
        "title": "Game Launcher",
        "description": "its a launcher to launch games",
        "long_description": "This Python program is a simple desktop game launcher built using the Tkinter GUI library. It allows the user to manage and launch games or programs from a single window.",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/game-launcher.svg",
        "screenshot": "images/screenshots/Screenshot game launcher.png",
        "file_name": "downloads/launcher1.exe",
        "author": STUDENT_NAME,
    },
     {
        "id": 5,
        "slug": "power-control",
        "title": "Power Control",
        "description": "shut down your computer after a timer",
        "long_description": "Ultra Power Manager Pro is a simple Tkinter-based Windows app that lets users schedule system shutdowns or restarts with a countdown timer, cancel active commands, and view basic system info through an easy-to-use graphical interface.",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/power-control.svg",
        "screenshot": "images/screenshots/Screenshot power control.png",
        "file_name": "downloads/power-manager1.exe",
        "author": STUDENT_NAME,
    },
     {
        "id": 6,
        "slug": "cyber-hunter",
        "title": "Cyber Hunter",
        "description": "its a mouse accuracy game",
        "long_description": "Cyber Hunter 2026 is a fast-paced, click-based arcade game built with Python and Tkinter. Your mission is simple: hunt the moving cyber target 👾, rack up points, and survive as the game speeds up with each level. Quick reflexes are rewarded. Miss too many clicks, and it’s game over.",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/cyber-hunter.svg",
        "screenshot": "images/screenshots/Screenshot cyber hunter.png",
        "file_name": "downloads/cyberhunter1.exe",
        "author": STUDENT_NAME,
    },
     {
        "id": 7,
        "slug": "wallpaper-changer",
        "title": "Wallpaper Changer",
        "description": "it changes you wallpaper for you😁",
        "long_description": "A modern desktop wallpaper changer built with CustomTkinter that automatically downloads high-resolution images based on selected categories and sets them as your Windows wallpaper. The app supports manual wallpaper changes as well as automatic timed intervals, with a built-in preview feature and progress feedback.",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/wallpaper-changer.svg",
        "screenshot": "images/screenshots/Screenshot wallpaper changer.png",
        "file_name": "downloads/wallpaper-changer.exe",
        "author": STUDENT_NAME,
    },
     {
        "id": 8,
        "slug": "smart-organizer",
        "title": "Smart Organizer",
        "description": "auto organizes your files in your folders",
        "long_description": "A lightweight desktop application built with Python and Tkinter that automatically organizes files in a selected folder into categorized subfolders (Images, Documents, Audio, Videos, and Other).",
        "category": "Utility",
        "version": "1.0.0",
        "icon": "images/icons/smart-organizer.svg",
        "screenshot": "images/screenshots/Screenshot smart organizer.png",
        "file_name": "downloads/Smart-organizer.exe",
        "author": STUDENT_NAME,
    },
]
